#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

## check if the install.conf file exists and import it if it does.
if [[ -f ./install.conf ]]
  ## This file is imported for the variables used in this file.
  then
  source ./install.conf
fi

if [[ ! -d "$bin" ]]
  then
  mkdir -p "$bin"
fi
if [[ ! -d "$conf" ]]
  then
  mkdir -p "$conf"
fi

for type in "${install_array[@]}"
  do
    eval "ref=\$$type"
    if [[ -d "$ref" ]]
      then
      printf '\n%s %s\n\n' "Creating directory:" "$ref"
      mkdir -p "$ref"
    fi
  printf '\n%s %s\n\n' "The type of type is:" "$type"
  if [[ -d "$type" ]]
    then
    for file in ./"$type"/*
    do
      printf '%s %s %s %s\n' "Adding file to source:" "$file" "for" "$ref"
      source+=( "$file" )
    done
  fi
  ## add installation stuff here.
unset source
unset -n ref
done

read
