#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

## defines the usage of the program.
usage="
Name: 					lucid-build


Description:    			lucid-build compiles all PKGBUILD's recursively 
					within the working directory. It has options to
					modify where it starts searching and what
					architecture you would like to build within that
					working directory.
					
					It also allows the user to choose the location
					of their final repository and sub repository.
					
					Currently you can only use one architecture at
					a time but that may change in the future.


Usage:					lucid-build (Options) [-d] <location>

Options: 		

	-h or --help 			You're reading it.
	
	-6				Compiles x86_64 packages.
	
	-3				Compiles i686 packages.
	
	-m				Compiles multilib packages.
					
	-d				Specifies the directory to start searching for
					PKGBUILD files.
					
	-t				This specifies the repository target. This location
					is modified by this script to place things in a
					proper repository location for the proper arch.
					Default: /var/lucid/repo
					
	-r				This will select the final repository the packages 
					are to be built in. 
					eg. core, extra, community, multilib.
					Default: unstable
					
					
Examples:		
	The following examples will compile packages for the appropriate 
	architecture starting in the current working directory.
	
	lb -6
	lb -3
	lb -m
	
	The following examples will compile packages for the appropriate
	architecture at the location you point it at.
	
	lb -6d /var/abs/core/pacman -t /var/lucid/repo -r core
	lb -3d /var/abs/core/pacman -t /var/lucid/repo -r core
	lb -md /var/abs/multilib/zsnes -t /var/lucid/repo -r multilib"


## The main stuff.

## Check for root! If the user is not running the script as root advise
## that root is required to operate this script and then drop out. If
## The user is 
if [ "$EUID" != "0" ]; then
    printf "error: This script must be run as root.\n"
    exit 1
else

	OPTIND=1 ## make sure the optargs are reset for getopts
	buildtype="" ## makes sure there is a default set for build.
	dir=""	 ## makes sure there is a default set for dir.
	build="lucid-build"

## This case statement sets the build parameters of the program for
## which architecture to use. 
	while getopts "36d:hmt:r:" opt; do
		case "$opt" in
			d)	dir=$OPTARG;;
			6)	buildtype="unstable-x86_64-build"
					archtype="x86_64"
					printf "The build has been set to 64 bit.\n";;
			3)	buildtype="unstable-i686-build"
					archtype="i686"
					printf "The build has been set to 32 bit.\n";;
			m)	buildtype="unstable-multilib-build"
					archtype="x86_64"
					printf "The build has been set to multilib.\n";;
			t)	repodir=$OPTARG;;
			r)  repo=$OPTARG;;
			h)	printf printf '%s\n' "$usage"; exit 0;;
			\?)	printf printf '%s\n' "$usage" >&2; exit 1;;
		esac
	done
	
## Check and make sure the proper build parameters are set, if they are 
## not currently set then set the build options to reasonable 
## default options.
	if [ "$buildtype" = "" ]; then ## if no arch is select set one.
		buildtype="unstable-x86_64-build"
		archtype="x86_64"
		printf "The build has been set to $archtype as default.\n"
	else
		printf "The build environment being used is: %s\n" "$archtype"
	fi
	if [ "$dir" = "" ]; then ## if no directory selected set one.
		dir="./"
		printf "Finding packagebuilds in "pwd" directory.\n"
	else 
		printf "Finding packagebuilds in $dir directory.\n"
	fi
	if [ "$repodir" = "" ]; then ## if no repodir is selected set one.
		repodir="/var/lucid/repo"
		printf "Using $repodir as the default repository location\n"
	else
		printf "Using $repodir as the repository location\n"
	fi
	if [ "$repo" = "" ]; then ## if no repo is set the set one.
		repo="unstable"
	fi
	
	## Finally find the pkgbuilds and build them!
	find "$dir" -name PKGBUILD -type f -execdir "$build" "$buildtype" "$archtype" "$repodir/$archtype/$repo" \;
fi
