#!/usr/bin/env bash
##Created by Edward "edge226" Tunnah.

## This is the script that actually builds the packages in the build
## area and then moves everything out of the respective build areas into
## a staging area to be processed. This script should always be run
## through the shorter lb command instead of manually since it will always
## pass the parameters in the same way.

## Deal with incoming parameters here.
build="$1" ## The program that starts the actual build.
archtype="$2" ## The architecture. ie x86_64 or i686.
repo="$3" ## location for the repository to go. Packages go here.

## Set parameters for the program to be able to move all the resulting
## packages where they need to go.
pkg=".pkg.tar.xz" ## This mixed with $archtype allows me to know the pkg.
srcdir="$repo/src/" ## The src location.
logdir="$repo/log/" ## The log location.
echo "$repo"

## Do the build.
"$build"

## Create the appropriate repository directories.
mkdir -p "$repo" "$logdir" "$srcdir"

## Copy the Sources, Packages and logs to the appropriate directories.
## also has the benefitted effect of cleaning the working directory also
## add some for loops with conditional globs to check and see if these files exist then move them. This will
## get rid of the harmless error that happens when these files do not exist.
mv *debug* "$logdir" ## Copying this before $pkg makes sure all debug files have been moved to the correct place.
mv *.log "$logdir" ## This does contain some tar files so I copy it before $pkg. This leaves only $pkg and $src info left
mv *"$archtype$pkg" "$repo" ## Copy the pkg into the repo.
mv *"any$pkg" "$repo" ## Copy any files for all architectures were compiled move them into the repo.
mv *.tar.* "$srcdir" ## Copy source files to their directory.
